### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by PetrDlouhy**
Not ready yet

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
@adamcharnock This should be ready to be merged. It has github actions and Django 4 fixes. 

After this is released, I can make changes to the hordak actions.

**Comment by adamcharnock** [comment]
Great work @PetrDlouhy. Go ahead and hit the merge button – I'm happy for you to do so for both this and the subsequent changes.

**Comment by PetrDlouhy** [comment]
Many thanks @adamcharnock. It is now merged and all tests are green. I would need also pypi permissions or you to release the new version. My username is petr.dlouhy

**Comment by adamcharnock** [comment]
Invites sent!

**Pull request merged**
