### PR TITLE
Django 3.0 & Python 3.7/3.8 Support

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by adamcharnock** [comment]
Thank you for this @PetrDlouhy! It looks like the CI is still deeply unhappy. Your changes are a step in the right direction, but I think more work is going to be required. I think the following are still needed:

- [ ] Getting the [test settings](https://github.com/adamcharnock/django-smalluuid/blob/master/tests/settings.py) up to speed (needs updating for newer Django versions, see CI errors)
- [ ] Let's drop Python 3.4 support
- [ ] Add support for Pythons 3.7 & 3.8
- [ ] Drop support for Django < 1.11

You're welcome to do this @PetrDlouhy, but it is definitely not expected of you. Anyone else is welcome to have a go too. I don't think I'll get a chance to do it myself anytime soon.

[I recently did the same work](https://github.com/adamcharnock/django-su/compare/f6c0071d82a24627824a75e9c885f53a0744b94b...856efc83fade37fbec63dc3672ecaca90fd42211) on another package I maintain (django-su), so perhaps that would be a starting point.

**Comment by PetrDlouhy** [comment]
@adamcharnock I think, that now is everything fixed, except for this issue in `smalluuid`: https://github.com/adamcharnock/smalluuid/pull/2
Also Python 3.9 nightly doesn't pass because lack of Django support so I moved them to `allow_failures` section.

**Comment by PetrDlouhy** [comment]
@adamcharnock Can I do anything else to get this pulled?

**Comment by delissonjunio** [comment]
@adamcharnock Just to follow up here, anything we can do to help get this accross the finish line? It seems travis and coveralls are still not happy.

**Comment by adamcharnock** [comment]
Hi @PetrDlouhy and @adamcharnock, sorry for going quiet on this one. Thank you for bringing it to my attention. It looks like this test is still failing for Python 3.8:

```
======================================================================

FAIL: test_value_created (tests.testapp.tests.TypedModelTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/adamcharnock/django-smalluuid/tests/testapp/tests.py", line 118, in test_value_created

    self.assertEqual(model.uuid.type, 42)

AssertionError: 57 != 42

----------------------------------------------------------------------
```

Once that is fixed I will happily merge ASAP

**Comment by adamcharnock** [comment]
In my hurry to catchup on this issue I overlooked the related issue (https://github.com/adamcharnock/smalluuid/pull/2) which should resolve this. Give me 5 mins

**Comment by adamcharnock** [comment]
Hi @PetrDlouhy, I just wanted to add a thank you too. Thank you for submitting this and then also following up on my requests, I appreciate it very much. I don't make much use of this project myself, so you help in keeping it up to date is great.

With that in mind, I'd be happy to add you as a maintainer if it would interest you. There would be no obligation for you, but my hope would be that you'd be more inclined to fix problems such as this if you didn't have to go via me :-)

**Comment by adamcharnock** [comment]
Version `1.2.0` released

**Pull request merged**
